---
profile::horizon:
  - horizon
  - memcached

profile::keystone_api:
  - keystone
  - keystone::endpoint
#  - keystone_extra
  - keystone::roles::admin
  - keystone::db::mysql
#  - keystone::wsgi::apache

profile::glance_api:
  - glance::api
  - glance::registry
  - glance::db::mysql
  - glance::keystone::auth
  - glance::backend::file

profile::mysql:
  - mysql::server

profile::neutron_agents:
  - neutron
  - neutron::agents::metadata
  - neutron::agents::l3
  - neutron::agents::dhcp
  - neutron::plugins::ml2
  - neutron::agents::ml2::ovs

profile::neutron_api:
  - neutron
  - neutron::db::mysql
  - neutron::keystone::auth
  - neutron::server
  - neutron::server::notifications
  - neutron::plugins::ml2 #?
  - neutron::agents::ml2::ovs #?

profile::neutron_compute:
  - nova::network::neutron
  - nova::compute::neutron
  - neutron
  - neutron::plugins::ml2
  - neutron::agents::ml2::ovs

profile::nova_api:
  - nova
  - nova::network::neutron #?
  - nova::api
  - nova::conductor
  - nova::db::mysql
  - nova::keystone::auth
  - nova::scheduler

profile::nova_compute:
  - nova
  - nova::compute
  - nova::compute::libvirt

profile::rabbitmq:
  - rabbitmq
